repoURL: 'https://github.com/kiyeongkil/prac_by_term_infra.git'
apps:
  - name: prac-by-term
    project: default
    namespace: default
    source:
      path: prac-by-term
      customValues: true
      values:
        - values.yaml
  - name: prometheus
    project: default
    namespace: prom
    source:
      path: prometheus
      customValues: true
      values:
        - values-local.yaml
  - name: grafana
    project: default
    namespace: grafana
    source:
      path: grafana
      customValues: true
      values:
        - values-local.yaml