replicas: 1
image:
  repository: 364481446289.dkr.ecr.ap-northeast-2.amazonaws.com/demo
  tag: 1.0.0
  imagePullSecrets:
    - name: ecr-cred
service:
  type: NodePort
  protocol: TCP
  targetPort: 8080
  port: 8080
  nodePort: 31080
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=prod,Name=demo-alb
